// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVJEqnWxsXvjKQfE9OI7UOko0jUCvHU8Y',
    appId: '1:787077151055:web:36d6eac34d6e4379abed3a',
    messagingSenderId: '787077151055',
    projectId: 'course-correct-a2d9b',
    authDomain: 'course-correct-a2d9b.firebaseapp.com',
    storageBucket: 'course-correct-a2d9b.firebasestorage.app',
    measurementId: 'G-89015KKGDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnrD5qtCgJf1RfGbHa2UT7fK7PZo17hr8',
    appId: '1:787077151055:android:7f8c457af8606612abed3a',
    messagingSenderId: '787077151055',
    projectId: 'course-correct-a2d9b',
    storageBucket: 'course-correct-a2d9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnuRqLY8APv6CFFIRZsO4vASuoJ9kLgBQ',
    appId: '1:787077151055:ios:3852c255a8172a47abed3a',
    messagingSenderId: '787077151055',
    projectId: 'course-correct-a2d9b',
    storageBucket: 'course-correct-a2d9b.firebasestorage.app',
    iosBundleId: 'com.example.coursecorrect.courseCorrect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnuRqLY8APv6CFFIRZsO4vASuoJ9kLgBQ',
    appId: '1:787077151055:ios:3852c255a8172a47abed3a',
    messagingSenderId: '787077151055',
    projectId: 'course-correct-a2d9b',
    storageBucket: 'course-correct-a2d9b.firebasestorage.app',
    iosBundleId: 'com.example.coursecorrect.courseCorrect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVJEqnWxsXvjKQfE9OI7UOko0jUCvHU8Y',
    appId: '1:787077151055:web:342f112fcb6ff06eabed3a',
    messagingSenderId: '787077151055',
    projectId: 'course-correct-a2d9b',
    authDomain: 'course-correct-a2d9b.firebaseapp.com',
    storageBucket: 'course-correct-a2d9b.firebasestorage.app',
    measurementId: 'G-GTG5XKLX54',
  );
}
